package com.hjy.sacore.dao.logcenter;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.hjy.sacore.entity.logcenter.LcStockchange;
import com.hjy.sacore.entity.logcenter.LcStockchangeExample;

public interface ILcStockchangeDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int countByExample(LcStockchangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(LcStockchangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer zid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int insert(LcStockchange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int insertSelective(LcStockchange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	List<LcStockchange> selectByExample(LcStockchangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	LcStockchange selectByPrimaryKey(Integer zid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") LcStockchange record, @Param("example") LcStockchangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") LcStockchange record, @Param("example") LcStockchangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(LcStockchange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table lc_stockchange
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(LcStockchange record);
}