package com.hjy.sacore.dao.systemcenter;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.hjy.sacore.entity.systemcenter.ScStoreSkunum;
import com.hjy.sacore.entity.systemcenter.ScStoreSkunumExample;

public interface IScStoreSkunumDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int countByExample(ScStoreSkunumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int deleteByExample(ScStoreSkunumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer zid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int insert(ScStoreSkunum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int insertSelective(ScStoreSkunum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	List<ScStoreSkunum> selectByExample(ScStoreSkunumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	ScStoreSkunum selectByPrimaryKey(Integer zid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ScStoreSkunum record, @Param("example") ScStoreSkunumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ScStoreSkunum record, @Param("example") ScStoreSkunumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ScStoreSkunum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc_store_skunum
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ScStoreSkunum record);

	/***
	 * 修改库存 减库存
	 * 
	 * @param record
	 * @return
	 */
	int updateStock_num(ScStoreSkunum record);

	/**
	 * 加库存
	 * 
	 * @param record
	 * @return
	 */
	int addStock_num(ScStoreSkunum record);

	/**
	 * 加锁
	 * 
	 * @param record
	 * @return
	 */
	int updateStockBylock(ScStoreSkunum record);

}